### ISSUE TITLE
Gehennom redesign

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1024]
Maybe do so that random levels in Gehennom had two variants:

1. Maze
2. Gnomish Mines

This would already reduce some tedium and add variation.

**Comment by TommiGustafsson-HMP** [comment]
Some special rooms/areas would also add variation to mazes and gnomish mines levels.

**Comment by TommiGustafsson-HMP** [comment]
Third variant could be the one with wide corridors.

**Comment by janne-hmp** [comment]
Done. 2/3 of all non-special levels are gnomish mine style, since all special levels have to use maze (narrow or wide corridors; so there will be a lot of maze to start with, unless one wants to remove them by hand from special levels). There is now also a gnomish-mines style lair of the Tarrasque in the Gehennom. Gnomish mines style maps are now colored in Gnomish mines (brown) and Hell (orange).
