### ISSUE TITLE
Fountains of Power too generous?

### ISSUE THREAD

**Issue by stormneedle** [hyvanmielenpelit/GnollHack#1092]
![Annotation 2020-06-03 130248](https://user-images.githubusercontent.com/36433826/83683646-96192b80-a59a-11ea-96e3-5e41d480faa8.png)

I like it, but if I drink from most fountains except poison, they disappear after a single draft.
Windows GnollHack Version 4.0.23 - last build Sun May  3 14:28:55 2020 (x64).

**Comment by janne-hmp** [comment]
Thanks for the report. That is a very rare _blessed_ fountain of power, which also gives a bit of maximum hit points and mana. In any case, due to a coding or planning error, the fountains do not dry up, except for the normal NetHack fountain (which is called the magic fountain). I just fixed this in the source code, and this will be fixed in the new patch.

**Comment by janne-hmp** [comment]
HI, just to confirm, I fixed this now and updated the servers.
