### ISSUE TITLE
Skills leveling incorrectly

### ISSUE THREAD

**Issue by TheJazziestCat** [hyvanmielenpelit/GnollHack#1118]
Training skills results in the wrong skill becoming available for enhancement. I'm currently playing a human monk, and I've advanced in divination spells, movement spells, and now abjuration spells, despite not having cast any of those spells. I didn't catch the first two, but abjuration spells became available immediately after performing an unarmed strike (and leveling up as a result).

I'm playing on the US Ohio server, running linux if it makes a difference.

**Comment by janne-hmp** [comment]
Hi, we changed how the spell skill advancement works in GnollHack compared to NetHack. I tried to look when that was changed, but couldn't immediately find this, although this probably was done some time in April. Also, it seems that the wiki may not be up-to-date regarding this change. We have been working on a massive update to the game for about two months now, and there has been a bit less focus lately on updating the wiki recently.

In any case, we felt that some spell schools were unnecessarily difficult to advance, since one casts their spells relatively rarely and not frequently like attack spells. Casting of the spells in certain spell schools may also be limited by available material components. Basically, just the arcane school (attack) spells would be cast often enough to ensure advancement by training. Now the system works so that you can advance spell skills _either_ by training _or_ by level. Each class has a preset system when various skill levels become available, regardless of training, in order to increase options for allocating skill points for spell-casting classes. This is part of our efforts to improve spell-casting classes. Non-spell skills work just by training, although there is an option to define a level-based advancement for them as well.

**Comment by TheJazziestCat** [comment]
Ohhhh, that makes sense, thank you. I was wondering if it was intentional—I thought I might have been getting skill gain from reading spellbooks. The leveling thing makes sense, though.
-------- Original Message --------
