### ISSUE TITLE
Make Creature-Bane Weapons have 15% chance of instakilling a monster of that type

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1245]
It could be a death attack, so death resistance nullifies it. Then, naturally, demon bane does not kill death-resistant demons. It could be also subject to MC.

**Comment by janne-hmp** [comment]
Done. They all are normal attacks with no saving throw, to make them more special. However, to unique monsters, they cause 25% of max HP damage instead of death. Removed Gnollbane and warhammer of gnoll slaying, because they would be too dangerous against player gnolls, and also sword of orc slaying as too dangerous against player orcs and otherwise being generally quite useless.
