### ISSUE TITLE
Wand of cancellation seems to be overpowered against boss monsters

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1341]
Now that it skips magic resistance.

**Comment by janne-hmp** [comment]
Fixed. It is now so that unique monsters get magic resistance check while non-uniques don't. However, there is a 10th level spell called Disjunction that causes cancellation and bypasses unique monster magic resistance. There is also a new artifact called Rod of Disjunction that acts like a wand of disjunction.
