### ISSUE TITLE
While wielding Grayswandir and being unaffected by black light keeps on telling "looks uninteresting"

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#171]
The text comes once in a while, even though Grayswandir protects from hallucination. The text is the same that comes when the hallucination ends.

**Comment by janne-hmp** [comment]
This seems to be a bug (poor coding) in NetHack 3.6.2.

**Comment by janne-hmp** [comment]
Artifact data structure is pretty poorly done. Currently, normal item data structure can do almost everything the artifacts can. It would be possible to change artifacts so that they are normal items, possibly referencing a base item. E.g. Grayswandir would be an item for which the base item is silver saber. The abilities of Grayswandir item and its base item would be added together.

In the same way, Staff of the Magi could have a quarterstaff as a base item.

**Comment by janne-hmp** [comment]
Should be fixed now.
