### ISSUE TITLE
Segfault on game end, prevents writing data to logfile/record/xlogfile files

### ISSUE THREAD

**Issue by k21971** [hyvanmielenpelit/GnollHack#1910]
This is on version 4.1.0.29 hot fix 1 (tested against binary compiled up to commit 9614b358bd3f630862f7caa0ed7d7e36248653d4). Crash is inconsistent, sometimes it happens immediately on answering yes to 'do you want your possessions identified', can also happen right after 'do you want to see dungeon overview' whether answering yes or no. Regardless of when the segfault occurs, the coredump is the same.

See https://termbin.com/pbyh

**Comment by janne-hmp** [comment]
This seems to be caused by the menu_head_objsym option being on. It should have crashed the game when opening the inventory immediately, regardless of whether at the end or not. In any case, I fixed it now. It related to deducting a bigger size_t from a smaller size_t, resulting in a very big number rather than a negative. I might have changed the variables to size_t at some point due to use with strlen. The current fixed build is actually good to Hardfought now.
