### ISSUE TITLE
Panic crash after descending level 10

### ISSUE THREAD

**Issue by DavidAnt900** [hyvanmielenpelit/GnollHack#1933]
Android version. As per the title, "panic!" crash upon descending to level 10 and was left with an irrecoverable save file. I'm pretty bummed out I had quite a bit of time in this character and he was looking good. Crash report attached, thank you for your time.
~Dave

[crash_report.zip](https://github.com/hyvanmielenpelit/GnollHack/files/9713315/crash_report.zip)

**Comment by TommiGustafsson-HMP** [comment]
We are very sorry about this, but we are about to release a patch that addresses panic crashes later this week. Thank you for your patience.

**Comment by janne-hmp** [comment]
This has been fixed so that you can now load panic save files on Android (works if not corrupted). Also, this particular panic will not happen going forward due to new checks in the function causing panic, but the root cause of the panic still remains unclear (i.e., the reason why the function was called with the wrong argument).

**Comment by janne-hmp** [comment]
Fixed also the root cause now.
