### ISSUE TITLE
A potion of extra healing did not cure a pet's mummy rot

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1991]
Source: https://discord.com/channels/205277826788622337/400474774440247317/1117808378593419306

According to this: https://github.com/hyvanmielenpelit/GnollHack/wiki/How-to-Cure-Various-Conditions
it should do so.

**Comment by janne-hmp** [comment]
It is only a blessed potion of extra healing that works, but uncursed greater healing or full healing. There was a mistake in the wiki. Otherwise, sicknesses would a bit too easy to cure. Can be changed to be easier going forward, if need be. At the moment, terminal illness and mummy rot are equally difficult to cure.
