### ISSUE TITLE
Add UI scaling/zooming to Modern Windows app (1440p)

### ISSUE THREAD

**Issue by Hash56** [hyvanmielenpelit/GnollHack#2087]
Playing on a 2560 x 1440p screen, all texts are very small. Changing resolution to 1080p works but of course makes things blurry

**Comment by TommiGustafsson-HMP** [comment]
It should do this automatically. Would you please mind sharing some screenshots:

In Gnollhack:
- A screenshot of the problem
- A screenshot of About→Version page?

In Windows' Settings App:
- In System→Display page, the Scale & layout section
- System→Display→Advanced display page, the whole page

**Comment by janne-hmp** [comment]
Added a custom screen scale option to Settings. It should work well on large desktop screens, but on smaller ones needing automatic screen scaling, it interacts with automatic screen scaling algorithm so that things may stay about the same after the algorithm is run (i.e., the algorithm may scale things down the same amount as the custom scaling is up). The new release is on the way to Microsoft Store.
