### ISSUE TITLE
Rusting/corroding to lower MC as well?

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#292]
Should eroding effects reduce MC as well?

Enchantment affects only AC, that's ok. But eroding can be different.

**Comment by janne-hmp** [comment]
Enchantment can actually be market to affect MC using O1_SPE_AFFECTS_MC flag, but this is currently in use only for Sword of Holy Vengeance. There is now another flag that can be used to remove (default) eroding effect on MC. All items providing MC by oc_magic_cancellation are otherwise affected by erosion by default.
