### ISSUE TITLE
Make drowning a delayed instadeath

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#447]
So that it does not kill you instantly but after some time like in reality.

**Comment by janne-hmp** [comment]
Then it sounds like it does almost never kills you. If drop into a pool, you just climb back, or perhaps move a few squares while drowning and then crawl up, which enables you to bypass moats etc... Instakill by eels and krakens are easy to fix, though, as they are a bit differently implemented. They can be implemented as suffocation akin to Amulet of Strangulation.

What should be the mechanics here for entering the moat without magical breathing or swimming?

**Comment by TommiGustafsson-HMP** [comment]
Entering a moat could still be instadeath or so, but sea creatures' instadeath could be nerfed.

**Comment by janne-hmp** [comment]
Sea creatures' attack has been changed as follows: Instead of instakilling at 10% chance on successful hit (required two successive hits, actually), the creature now has a 50% chance of wrapping around you on a successful hit. If successful, there are 6 rounds to get released before the drowning happens -- The same as with amulet of strangulation. I think this makes the sea monsters cooler -- They strangle more often. The player hitting other monsters in a polymorphed form still uses the old system.
