### ISSUE TITLE
Fix martial arts

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#465]
- Martial artist uses martial arts damage 100% of the time instead of 75%. Now 1/4 of hits are normal hits, which do not use damage bonuses or something like that.
- Martial artist gets multiple attacks per skill level: Basic 1, Skilled 1d2, Expert 2, Master 1d2+1, Grand Master 3
- Gloves' enchantment bonus adds to both attack to-hit and attack damage
- Martial arts gets full Strength and Dexterity to-hit and damage bonuses

**Comment by janne-hmp** [comment]
Ok, will do also Spiked Gauntlets, which can be used in bare handed combat for extra damage. But maybe not in martial arts, except maybe by Orcs and Gnolls.

**Comment by janne-hmp** [comment]
How about two-weapon fighting, i.e., martial artist with attacking with both right and left hand. Otherwise, in two weapon fighting, a non-monk character attacks once with both hands, i.e., two times per round, or if holding a shield, then with the right fist and the shield in left hand.

**Comment by TommiGustafsson-HMP** [comment]
Also, martial artist could kick monsters, causing them to back off one square and be stunned, like jousting. This would not be applied with normal melee attacks, but using the kick command.

**Comment by janne-hmp** [comment]
Fixed. 75% mechanism cannot be found, probably a non-existing thing. Other changes are:
- Base damage for bare handed is 1d2, for martial arts 1d4 / 1d6 / 1d8
- Strength bonus is normally 50% of full STR damage, for martial arts 75%, 100%, and 150%
- DEX to-hit-bonuses are always applied in all cases
- Bare handed fighting gives (starting unskilled) -1/+0/+1/+2 to hit
- Bare handed fighting gives (starting unskilled) +0/+1/+2/+3 to damage
- Martial arts gives (starting unskilled) +0/+2/+4/+6 to hit
- Martial arts gives (starting unskilled) +0/+2/+4/+6 to damage
- Martial arts is exercised by kicking and by bare handed combat when the bare handed skill has reached expert level
- Skill in Martial Arts requires XP as though it were skill levels 4-6
- # of hits per hand is normally 1, for martial arts 1/1d2/2
- Gloves give their damage and enchantment plus to damage
- Metallic gloves disallow Martial Arts bonuses
- Boots give their damage and enchantment plus to damage when kicking
- Metallic boots disallow Martial Arts bonuses, except when they are magical Kicking Boots
- Magical Kicking gives full STR damage bonus, otherwise only half, except with Martial Arts
- Kicking has -2 base to hit adjustment
- Fumbling or bulky armor gives extra -4 to hit
- Martial artist (25%/33%/50%) and magical kicking (50%) have a chance of either hurtling the opponent backward or making him or her reel  (almost the same effect).
