### ISSUE TITLE
Damage per mana & mana pool

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#48]
Let's balance the damage per mana so that 1 mana = 1 damage.
Thus, Cone of Cold, level 5, doing 15d6 damage (average 52,5) will cost 50 mana.
Thus, all levels could be

- -1: 4 mana
- 0: 7 mana
- 1: 10 mana
- 2: 15 mana
- 3: 20 mana
- 4: 30 mana
- 5: 50 mana
- 6: 75 mana
- 7: 100 mana
- 8: 150 mana
- 9: 200 mana
- 10: 300 mana

Low levels would be more mana effective (maybe 1.5 damage per mana at level 0) and higher levels less mana effective (maybe 0.67 damage per mana at level 10).

Mana pool could be 20 mana per level for Wizard with Int 18. Thus, level 10 Wizard would have 200 mana, able to cast Cone of Cold 4 times.

**Comment by janne-hmp** [comment]
Mana is now determined so that (1) INT 18 gives 15/2 = (18-3)/2 = 7.5 mana per level, (2) Wizard class gives 1d6+4 = 7.5 mana per level, and (3) human race gives 1d6 = 3.5 mana per level. Total 18.5 mana per level. So half of mana comes from INT and half from training as a wizard, which little bit helps with barbarians or dwarves not coming suddenly great wizards.

Barbarians get 1d3 mana per level and dwarves get 0 mana per level, being non-magical, which though is not necessarily a huge disadvantage (only 3.5 mana per level). Elves get 1d8+2 = 6.5 mana per level, so an elven wizard with INT 18 makes 21.5 mana per level (in fact they may have INT 20, so they would have 23.5 mana per level).

**Comment by janne-hmp** [comment]
Spell mana costs updated. Mana pool works as per above.
