### ISSUE TITLE
Make pets regenerate HP faster?

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#537]
They seem to die pretty often.

**Comment by janne-hmp** [comment]
They regenerate 1 hp every 20 turns, which is the same with everybody, except regenerating monsters, which regenerate 1 hp per round. Maybe a different solution to the problem? Pets didn't die so often before, because monsters didn't hit them. Now both pets and monsters hit each other whenever possible, so obviously they die much more often.

**Comment by TommiGustafsson-HMP** [comment]
Maybe they can flee when on low hit points?

**Comment by TommiGustafsson-HMP** [comment]
And maybe monster constitution can increase hit point regeneration?
Player regenerates 1 hit point every 3 rounds when level 10+.
https://nethackwiki.com/wiki/Hit_points

So something could be done with pet HP regeneration.

**Comment by TommiGustafsson-HMP** [comment]
Maybe hit point regeneration could be MaxHP / 300 or MaxHP / 450 for all players and monsters, implemented in the same way as the mana regeneration?

**Comment by TommiGustafsson-HMP** [comment]
And the regeneration ability would double that.

**Comment by TommiGustafsson-HMP** [comment]
If starting hit points is about 20, and previously regeneration was 1 per 15 turns, it should be MaxHP/300. So, 20/300 = 1/15.

If HP at level 2 is about 30, 30/300 = 1/10, which quite well aligns with 1/11 that was before.

If HP at level 3 is about 40, 40/300 = 1/7,5, which is faster.

If HP at level 10 is about 110, 110/300 = 1/2,72.

Barbarian at level 10 (Con 18) is about 130 HP. 130/300 = 1/2,3

With 1/450 it would be

20/450 = 1/22,5, which seems a little bit low.
130/450 = 1/3,46, which seems also a little bit low

So 1/300 is quite ok, or 1/350.

**Comment by TommiGustafsson-HMP** [comment]
I think 1/300 is ok.

**Comment by janne-hmp** [comment]
Done. One may note that regeneration is not even over time; it is randomized so that the expected value is MaxHP/300. That is, if your HP is 75, then you have 25% chance of getting 1 hp every round. Not a big difference over many turns, but you may not get hit points for a long time, and then suddenly you get them many times every round, at least in extreme cases. In any case, mana regeneration works the same way.
