### ISSUE TITLE
Write a description for each (special) item

### ISSUE THREAD

**Issue by janne-hmp** [hyvanmielenpelit/GnollHack#654]

**Comment by TommiGustafsson-HMP** [comment]
Regarding to the comment on Reddit:
https://www.reddit.com/r/nethack/comments/ey9g2u/gnollhack_beta_public_server_usa_available_via/fgja0i0?utm_source=share&utm_medium=web2x

This is how FIQHack works:
https://drive.google.com/a/hyvanmielenpelit.fi/file/d/1fzv_GB9TEzWD1289jbeijBwOSLtOBZyd/view?usp=sharing

I think we don't need to implement anything like that, but it could be considered.

**Comment by TommiGustafsson-HMP** [comment]
Actually, this is a pretty good idea. If you click an item in your inventory screen 'i' (which normally does nothing), it will examine it 'Alt-x'.

**Comment by janne-hmp** [comment]
Ok, should be very easy to implement.

**Comment by SFPROXY** [comment]
I need to check how FIQHack handles an item categorized with the letter "i" because that might conflict with opening/closing inventory. There's a couple workarounds I can think of (maybe shift-i, or shift before any letter to perform an examine on said item?)

I just thought of this now so I thought I'd write this comment and mention it so that work is not done for something that may not perform well with the inventory system.

**Comment by janne-hmp** [comment]
Hi, many thanks for your comment. The proposed feature has now been there for 2 weeks in the game and works fine. That is, you can simply access ”examine” command also through ’i’ command.

**Comment by janne-hmp** [comment]
Done.
