### ISSUE TITLE
Rethink secret doors and secret corridors

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#678]
Secret doors and corridors can be a problem for new players. They do not know that they exist. Ville also experienced this #367 . There is some discussion about this on Reddit:

https://www.reddit.com/r/nethack/comments/f804oe/yani_rethink_secret_doors/

Maybe secret doors could not generate in the very first levels and find them could be 100% with 's' instead of 1/6 or so. But there are some ideas from other variant developers in the above link.

**Comment by TommiGustafsson-HMP** [comment]
Interesting start:

![image](https://user-images.githubusercontent.com/16661034/77756678-56811100-7038-11ea-8ff7-70f4d2e40008.png)

**Comment by FredrIQ** [comment]
Some approaches existing variants take, for inspiration.

* UnNetHack: Remove random generic secret doors and corridors (they can still be defined as part of special levels)
* FIQHack: Rework searching to immediately find doors and corridors next to you with zero or more Luck

Another idea I had personally when this came up elsewhere (when a veteran played a game spending 3k turns to find the Dlvl1 downstairs because of unusually obtuse level generation) was to, after a level is generated, pathfind between the upstair and downstair and, if unsuccessful, re-generate the level (Meaning there might still be secret passages, but you always have access to the downstair without searching).

**Comment by janne-hmp** [comment]
This has been fixed for difficulty levels less than expert.
