### ISSUE TITLE
Consistency for apply / invoke

### ISSUE THREAD

**Issue by janne-hmp** [hyvanmielenpelit/GnollHack#734]
Some consistency must be need for apply vs. invoke, but maybe only tools can be applied and everything else invoked, e.g. a polearm with charges. But then you can have conflict with an artifact polearm that is also a luckblade but has invokable artifact power. Maybe in that case invoke can ask whether you want to invoke the artifact on basic item power. Maybe nonappliable, invokable charged items should redirect one automatically to invoke instead of saying "cannot be applied"and invoke would ask that do you want to invoke the item.

**Comment by TommiGustafsson-HMP** [comment]
I think 'a' applying should be for normal powers, such as hitting with polearm or using a unicorn horn.

Invoke should be for special powers. For example, artifact powers or so. So, unicorn horn should be applied for its healing effect (normal power).

Luckblade, if implemented, should be Invoked for its special artifact power (wishing). It cannot be applied, since it has no normal power.

These should be consistent with NetHack so that old players do not get confused.

**Comment by janne-hmp** [comment]
Just as a note, luckblade is not an artifact, but a normal item with charges like wand of wishing.

**Comment by TommiGustafsson-HMP** [comment]
I think, it would be better as an artifact. But anyways, wishing is not its primary function, so it should be invoked, not applied.

**Comment by janne-hmp** [comment]
For the sake of clarity, only artifacts can be invoked. Nonartifact items are used by applying. If an item item requires an invoke ability, then it probably has to be designed to be an artifact. Consequently, Luckblade is an artifact.
