### ISSUE TITLE
Damage sustain message output even after enemy death

### ISSUE THREAD

**Issue by SFPROXY** [hyvanmielenpelit/GnollHack#735]
![Screenshot from 2020-03-11 13-46-45](https://user-images.githubusercontent.com/61036870/76447542-38ac7e80-639f-11ea-8f37-27e79c0e66c5.png)

this is a minor issue because sometime it's not clear if there is another enemy down the hall, or it's just the message from the monster you just shot. also troubling when the monster is invisible/out of sight and you get very vague messages like "It hits it!"

**Comment by janne-hmp** [comment]
Thanks. This was was an issue with spells. "It hit it!" messages should come when invisible or unseen monsters hit each other, and they do not currently display damage because the player is not a party to the fight. I also added for **pets** damage message as follows: "Hill orc hits the kitten. Kitten sustains 6 damage!". It was slightly complicated with the current code to display text similarly to the player ("Hill orc hits you for 6 damage."), as the amount of damage is not known in the code when it displays the hit message, and changing this would take quite a bit of work for such a small change. Maybe that's a further future improvement, but currently we can go like this.

**Comment by SFPROXY** [comment]
Hi, I'm not sure if you're saying it's not a bug or that it's been fixed. anyway, just hopped into a game on the public server, still seeing this. or at least, the damage sustain message after death. Not specifically the "It hits it!", I didn't try that out. Server reports:

Unix GnollHack Version 4.0.21 - last build Sun Mar  8 20:25:33 2020
 (0f8612844c0439fbec99583181f3975944796659).

![Screenshot from 2020-03-14 04-10-33](https://user-images.githubusercontent.com/61036870/76677954-1c306200-65aa-11ea-8d35-7c4c3095f585.png)

**Comment by janne-hmp** [comment]
Yes, the game server has not been updated yet, just the sources. The servers will be updated to 4.0.22 version some time in the future. We do not update the servers too often, since the updates often break save files. Quickest way to get the newest development version is to download the sources from GitHub to Windows or Linux, and compile to the game yourself from sources.

**Comment by janne-hmp** [comment]
Hi, the servers have been updated now. It is not an official release yet, but a number of bug fixes and new features are there now.
