### ISSUE TITLE
Strings in saved games do not work after rebuilding the solution

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#794]
To reproduce:

1. Start a game through Debug in Visual Studio
2. Wish for a fig, have some spells
3. Save and exit
4. Rebuild solution
5. Start the game through debug and load the saved game
6. Some strings do not work

In this case, the description was blank:

![image](https://user-images.githubusercontent.com/16661034/77040554-d36d1480-69c0-11ea-9c30-fa1262cc1e7c.png)

**Comment by TommiGustafsson-HMP** [comment]
And the saved game will crash after Run Code Analysis on solution:

![image](https://user-images.githubusercontent.com/16661034/77040984-b2f18a00-69c1-11ea-9926-6febf250eeee.png)

**Comment by janne-hmp** [comment]
Ok, this strings need to be saved separately in the save file, I think. Which they are not currently, just the pointers.

**Comment by TommiGustafsson-HMP** [comment]
Why is it saving these string pointers in the first place? Shouldn't the texts be the same in every game? So, why are they saved to the save file?

**Comment by janne-hmp** [comment]
Because it saves the objects array. The only reason for that as far as I know is that names are shuffled and there is the name_known flag that is being modified when an item becomes known. In contrast, monster base data array is not saved. But maybe I can move the new strings to where object’s shuffled name and description are stored.

**Comment by janne-hmp** [comment]
Let me also investigate if we can find a better system than storing the whole object array.

**Comment by janne-hmp** [comment]
Fixed.
